/**
 * Wallet system error codes and messages
 */

export enum WalletErrorCode {
  // Validation
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  AMOUNT_TOO_LOW = 'AMOUNT_TOO_LOW',
  AMOUNT_TOO_HIGH = 'AMOUNT_TOO_HIGH',

  // Balance
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_LOCKED = 'WALLET_LOCKED',
  WALLET_NOT_SETUP = 'WALLET_NOT_SETUP',

  // Limits
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
  MONTHLY_LIMIT_EXCEEDED = 'MONTHLY_LIMIT_EXCEEDED',
  TRANSACTION_LIMIT_EXCEEDED = 'TRANSACTION_LIMIT_EXCEEDED',

  // Bank Account
  INVALID_ACCOUNT_NUMBER = 'INVALID_ACCOUNT_NUMBER',
  ACCOUNT_VERIFICATION_FAILED = 'ACCOUNT_VERIFICATION_FAILED',
  BANK_ACCOUNT_NOT_FOUND = 'BANK_ACCOUNT_NOT_FOUND',
  DUPLICATE_BANK_ACCOUNT = 'DUPLICATE_BANK_ACCOUNT',

  // Transaction
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_PROCESSED = 'TRANSACTION_ALREADY_PROCESSED',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',

  // Paystack
  PAYSTACK_API_ERROR = 'PAYSTACK_API_ERROR',
  PAYMENT_INITIALIZATION_FAILED = 'PAYMENT_INITIALIZATION_FAILED',
  TRANSFER_FAILED = 'TRANSFER_FAILED',

  // Webhook
  INVALID_WEBHOOK_SIGNATURE = 'INVALID_WEBHOOK_SIGNATURE',

  // PIN
  INVALID_PIN = 'INVALID_PIN',
  PIN_LOCKED = 'PIN_LOCKED',
  PIN_NOT_SET = 'PIN_NOT_SET',

  // General
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export interface WalletError {
  code: WalletErrorCode;
  message: string;
  details?: Record<string, any>;
}

export function createWalletError(
  code: WalletErrorCode,
  message: string,
  details?: Record<string, any>
): WalletError {
  return { code, message, details };
}
